const state={run:null,product:null,viewAxes:[],perm:[],layer:0,isolate:false,currentOpacity:1,opacity:.25,opacityLinked:false,pixelDensity:96,scaleMin:0,scaleMax:1,logScale:false,yaw:.3,pitch:0,playing:false,timer:null,renderVersion:0,frame:0,volumes:new Map(),bitmaps:new Map(),coordinates:new Map(),theme:'dark',colorMap:'spviz',aspect:'data',overviewAspect:'data',viewMode:'surface'};
const $=id=>document.getElementById(id),hexColors=colors=>colors.map(hex=>[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5),16)]),colorMaps={spviz:hexColors(['#17213a','#6177ff','#28bfa7','#ed985f','#eb6170']),viridis:hexColors(['#440154','#3b528b','#21918c','#5ec962','#fde725']),plasma:hexColors(['#0d0887','#7e03a8','#cc4778','#f89540','#f0f921']),inferno:hexColors(['#000004','#420a68','#932667','#dd513a','#fcffa4']),magma:hexColors(['#000004','#3b0f70','#8c2981','#de4968','#fcfdbf']),cividis:hexColors(['#00224e','#434e6c','#7d7c78','#bcae6c','#fee838'])};
function palette(){return colorMaps[state.colorMap]}
function themeInk(){const style=getComputedStyle(document.documentElement);return{muted:style.getPropertyValue('--canvas-muted').trim(),label:style.getPropertyValue('--canvas-label').trim(),strong:style.getPropertyValue('--canvas-strong').trim(),line:style.getPropertyValue('--canvas-line').trim()}}
function updateScale(){const colors=colorMaps[state.colorMap].map(color=>`rgb(${color.join(',')})`),gradient=`linear-gradient(90deg,transparent 0%,${colors.map((color,index)=>`${color} ${(index+1)*100/colors.length}%`).join(',')})`;document.documentElement.style.setProperty('--colormap-gradient',gradient)}
function bytes(n){for(const u of ['B','KiB','MiB','GiB']){if(n<1024||u==='GiB')return `${n.toFixed(n<10&&u!=='B'?1:0)} ${u}`;n/=1024}}
function permutations(n){const out=[];function walk(a,left){if(!left.length)out.push(a);else left.forEach((v,i)=>walk([...a,v],[...left.slice(0,i),...left.slice(i+1)]))}walk([],Array.from({length:n},(_,i)=>i));return out}
function lruSet(cache,key,value,limit){cache.delete(key);cache.set(key,value);while(cache.size>limit)cache.delete(cache.keys().next().value)}
function setVolumeStatus(message,error=false){const status=$('volume-status');status.textContent=message;status.classList.toggle('visible',Boolean(message));status.classList.toggle('error',error)}
function qualityLimit(){return state.pixelDensity}
const staticBase=window.SPVIZ_STATIC_BASE;
if(window.SPVIZ_GALLERY_URL){$('gallery-link').href=window.SPVIZ_GALLERY_URL;$('gallery-link').hidden=false}
function downsampleVolume(volume,limit){const sourceRows=volume.rows,sourceColumns=volume.columns,rows=Math.min(sourceRows,limit),columns=Math.min(sourceColumns,limit);if(rows===sourceRows&&columns===sourceColumns)return volume;const values=new Float32Array(volume.depth*rows*columns);for(let depth=0;depth<volume.depth;depth++)for(let row=0;row<rows;row++){const sourceRow=Math.round(row*(sourceRows-1)/Math.max(1,rows-1));for(let column=0;column<columns;column++){const sourceColumn=Math.round(column*(sourceColumns-1)/Math.max(1,columns-1));values[(depth*rows+row)*columns+column]=volume.values[(depth*sourceRows+sourceRow)*sourceColumns+sourceColumn]}}return{...volume,rows,columns,shape:[volume.depth,rows,columns],values}}
async function getVolume(product,perm,limit=qualityLimit()){
  const key=`${product.id}:${perm.join(',')}:${limit}`,cached=state.volumes.get(key);if(cached){state.volumes.delete(key);state.volumes.set(key,cached);return cached}
  const stem=`${product.id}--${perm.join('-')}`,pending=(staticBase?Promise.all([fetch(`${staticBase}/volumes/${stem}.json`).then(response=>response.json()),fetch(`${staticBase}/volumes/${stem}.f32`).then(response=>response.arrayBuffer())]).then(([metadata,buffer])=>downsampleVolume({...metadata,values:new Float32Array(buffer)},limit)):fetch(`/api/product/${product.id}/volume?perm=${perm.join(',')}&limit=${limit}`).then(async response=>{if(!response.ok)throw new Error(await response.text());const metadata=JSON.parse(response.headers.get('X-Spviz-Metadata')),values=new Float32Array(await response.arrayBuffer());return{...metadata,values}})).then(result=>{lruSet(state.volumes,key,result,12);return result}).catch(error=>{state.volumes.delete(key);throw error});
  lruSet(state.volumes,key,pending,12);return pending
}
async function getSlice(product,perm,layer,limit=qualityLimit()){
  const volume=await getVolume(product,perm,limit),clamped=Math.max(0,Math.min(layer,volume.depth-1)),planeSize=volume.rows*volume.columns;
  return{...volume,layer:clamped,values:volume.values.subarray(clamped*planeSize,(clamped+1)*planeSize)}
}
async function getDisplayedSlice(product,perm,layer){const sliced2D=perm.length===2&&state.viewMode==='slices',slice=await getSlice(product,perm,layer,sliced2D?Math.max(qualityLimit(),product.shape[perm[0]]):qualityLimit());if(sliced2D){const row=Math.max(0,Math.min(layer,slice.rows-1));return{...slice,rows:1,depth:1,layer:row,source_plane_shape:[1,slice.source_plane_shape[1]],values:slice.values.subarray(row*slice.columns,(row+1)*slice.columns)}}return slice}
async function getCoordinates(product,axis){const key=`${product.id}:${axis}`;if(state.coordinates.has(key))return state.coordinates.get(key);const url=staticBase?`${staticBase}/coordinates/${product.id}--${axis}.json`:`/api/product/${product.id}/coordinates/${axis}`,pending=fetch(url).then(response=>response.json()).then(result=>{state.coordinates.set(key,result);return result});state.coordinates.set(key,pending);return pending}
function formatCoordinate(value){if(typeof value==='number')return Number.isInteger(value)?String(value):Number(value).toPrecision(4);return String(value)}
function coordinateLabel(axis,index){const descriptor=state.coordinates.get(`${state.product.id}:${axis}`);if(!descriptor||descriptor instanceof Promise)return String(index);const value=descriptor.values[Math.max(0,Math.min(index,descriptor.values.length-1))];return `${formatCoordinate(value)}${descriptor.units?` ${descriptor.units}`:''}`}
function axisRangeLabel(axis){const descriptor=state.coordinates.get(`${state.product.id}:${axis}`);if(!descriptor||descriptor instanceof Promise)return state.product.axes[axis];const first=formatCoordinate(descriptor.values[0]),last=formatCoordinate(descriptor.values[descriptor.values.length-1]),units=descriptor.units?` ${descriptor.units}`:'';return `${state.product.axes[axis]}: ${first} → ${last}${units}`}
function axisTitle(axis){const descriptor=state.coordinates.get(`${state.product.id}:${axis}`);return `${state.product.axes[axis]}${descriptor&&!(descriptor instanceof Promise)&&descriptor.units?` (${descriptor.units})`:''}`}
function axisTick(axis,fraction){const descriptor=state.coordinates.get(`${state.product.id}:${axis}`),size=state.product.shape[axis],index=Math.round(fraction*(size-1));if(!descriptor||descriptor instanceof Promise)return String(index);return formatCoordinate(descriptor.values[index])}
function drawSheetAxes(context,geometry){const{x,y,width,height,xAxis,yAxis,light=false}=geometry,ticks=[0,.25,.5,.75,1],muted=light?'#4b5568':'#91a0b8',label=light?'#283142':'#b7c2d6',strong=light?'#111827':'#eef2ff';context.save();context.strokeStyle=muted;context.fillStyle=label;context.lineWidth=1;context.font='11px system-ui';context.textAlign='center';context.beginPath();context.moveTo(x,y+height+7);context.lineTo(x+width,y+height+7);context.stroke();for(const fraction of ticks){const tx=x+fraction*width;context.beginPath();context.moveTo(tx,y+height+4);context.lineTo(tx,y+height+11);context.stroke();context.fillText(axisTick(xAxis,fraction),tx,y+height+24)}context.fillStyle=strong;context.font='12px system-ui';context.fillText(axisTitle(xAxis),x+width/2,y+height+41);if(yAxis!==null){context.strokeStyle=muted;context.fillStyle=label;context.font='11px system-ui';context.textAlign='right';context.beginPath();context.moveTo(x-7,y);context.lineTo(x-7,y+height);context.stroke();for(const fraction of ticks){const ty=y+fraction*height;context.beginPath();context.moveTo(x-11,ty);context.lineTo(x-4,ty);context.stroke();context.fillText(axisTick(yAxis,fraction),x-15,ty+4)}context.save();context.translate(x-66,y+height/2);context.rotate(-Math.PI/2);context.fillStyle=strong;context.font='12px system-ui';context.textAlign='center';context.fillText(axisTitle(yAxis),0,0);context.restore()}context.restore()}
function drawDepthAxis(context,axis,originX,originY,offsetX,offsetY,slots,selectedPosition,selectedLayer,light=false){if(slots<=1)return;const endX=originX+offsetX*(slots-1),endY=originY+offsetY*(slots-1),selectedX=originX+offsetX*selectedPosition,selectedY=originY+offsetY*selectedPosition,muted=light?'#4b5568':'#91a0b8',label=light?'#283142':'#b7c2d6',strong=light?'#111827':'#eef2ff';context.save();context.strokeStyle=muted;context.fillStyle=label;context.lineWidth=1;context.beginPath();context.moveTo(originX,originY-15);context.lineTo(endX,endY-15);context.stroke();for(const fraction of [0,.5,1]){const x=originX+(endX-originX)*fraction,y=originY-15+(endY-originY)*fraction,index=Math.round(fraction*(state.product.shape[axis]-1));context.beginPath();context.arc(x,y,2.5,0,Math.PI*2);context.fill();context.font='11px system-ui';context.textAlign='left';context.fillText(coordinateLabel(axis,index),x+6,y-4)}context.fillStyle=strong;context.beginPath();context.arc(selectedX,selectedY-15,4,0,Math.PI*2);context.fill();context.font='12px system-ui';context.fillText(`${axisTitle(axis)} · selected ${coordinateLabel(axis,selectedLayer)}`,selectedX+7,selectedY+15);context.restore()}
function drawAffineImage(context,image,x,y,u,v){context.save();context.transform(u.x/image.width,u.y/image.width,v.x/image.height,v.y/image.height,x,y);context.drawImage(image,0,0);context.restore()}
function strokeAffinePlane(context,x,y,u,v,color,width=1){context.save();context.strokeStyle=color;context.lineWidth=width;context.beginPath();context.moveTo(x,y);context.lineTo(x+u.x,y+u.y);context.lineTo(x+u.x+v.x,y+u.y+v.y);context.lineTo(x+v.x,y+v.y);context.closePath();context.stroke();context.restore()}
function drawProjectedAxes(context,geometry,light=false){const{x,y,u,v,xAxis,yAxis}=geometry,ink=light?{muted:'#4b5568',strong:'#111827'}:themeInk();context.save();context.strokeStyle=ink.muted;context.fillStyle=ink.strong;context.lineWidth=1.2;context.font='12px system-ui';context.beginPath();context.moveTo(x,y);context.lineTo(x+u.x,y+u.y);context.moveTo(x,y);context.lineTo(x+v.x,y+v.y);context.stroke();context.textAlign='center';context.fillText(axisTitle(xAxis),x+u.x/2-v.x*.08,y+u.y/2-v.y*.08);context.save();context.translate(x+v.x/2-u.x*.07,y+v.y/2-u.y*.07);context.rotate(Math.atan2(v.y,v.x)-Math.PI/2);context.fillText(axisTitle(yAxis),0,0);context.restore();context.restore()}
function canvasSize(canvas){const rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1;if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio)}const context=canvas.getContext('2d');context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,rect.width,rect.height);return{context,width:rect.width,height:rect.height}}
function scaleBounds(product,log,minFraction=0,maxFraction=1){const signed=product?.shape.length===1&&!product?.dtype.includes('complex'),statsMin=signed?(product?.stats.value_min??0):Math.max(0,product?.stats.min??0),configuredMin=product?.display_min,dataMin=signed?(configuredMin??statsMin):Math.max(0,configuredMin??statsMin),configuredMax=product?.display_max,dataMax=Math.max(dataMin+1e-12,configuredMax??(signed?product?.stats.value_max:product?.stats.max)??1);if(!log)return[dataMin+(dataMax-dataMin)*minFraction,dataMin+(dataMax-dataMin)*maxFraction];const floor=Math.max(dataMin,dataMax*1e-6,1e-12),lo=Math.log(floor),hi=Math.log(dataMax);return[Math.exp(lo+(hi-lo)*minFraction),Math.exp(lo+(hi-lo)*maxFraction)]}
function displayBounds(product=state.product){return scaleBounds(product,state.logScale,state.scaleMin,state.scaleMax)}
function tracePosition(value,min,max,log){if(log)return(Math.log(Math.max(1e-12,value))-Math.log(Math.max(1e-12,min)))/Math.max(1e-12,Math.log(Math.max(max,min*1.0001))-Math.log(Math.max(1e-12,min)));return(value-min)/Math.max(1e-12,max-min)}
function traceColor(fraction){const colors=palette(),scaled=Math.max(0,Math.min(1,fraction))*(colors.length-1),low=Math.floor(scaled),high=Math.min(colors.length-1,low+1),mix=scaled-low;return`rgb(${colors[low].map((channel,index)=>Math.round(channel+(colors[high][index]-channel)*mix)).join(',')})`}
function drawTrace(context,slice,x,y,width,height,min,max,log,light=false,alpha=1){const ink=light?{muted:'#4b5568',label:'#283142',strong:'#111827'}:themeInk(),values=slice.values,points=[],traceRgb=palette()[Math.min(2,palette().length-1)],traceColor=`rgb(${traceRgb.join(',')})`;context.save();context.globalAlpha=alpha;context.lineCap='round';context.lineJoin='round';context.strokeStyle=ink.muted;context.lineWidth=1;context.globalAlpha=.16*alpha;for(const fraction of [0,.25,.5,.75,1]){const gy=y+fraction*height;context.beginPath();context.moveTo(x,gy);context.lineTo(x+width,gy);context.stroke()}for(const fraction of [0,.25,.5,.75,1]){const gx=x+fraction*width;context.beginPath();context.moveTo(gx,y);context.lineTo(gx,y+height);context.stroke()}for(let i=0;i<values.length;i++){const value=values[i];if(!Number.isFinite(value))continue;const fraction=Math.max(0,Math.min(1,tracePosition(value,min,max,log)));points.push([x+i*width/Math.max(1,values.length-1),y+height*(1-fraction)])}if(points.length>1){context.globalAlpha=.10*alpha;context.fillStyle=traceColor;context.beginPath();context.moveTo(points[0][0],y+height);for(const point of points)context.lineTo(point[0],point[1]);context.lineTo(points.at(-1)[0],y+height);context.closePath();context.fill();context.globalAlpha=alpha;context.strokeStyle=traceColor;context.lineWidth=2;context.beginPath();context.moveTo(points[0][0],points[0][1]);for(const point of points.slice(1))context.lineTo(point[0],point[1]);context.stroke()}context.globalAlpha=.55*alpha;context.strokeStyle=ink.muted;context.lineWidth=1;context.strokeRect(x,y,width,height);if(min<0&&max>0){const zeroY=y+height*(1-tracePosition(0,min,max,false));context.globalAlpha=.65*alpha;context.beginPath();context.moveTo(x,zeroY);context.lineTo(x+width,zeroY);context.stroke()}context.globalAlpha=alpha;context.fillStyle=ink.label;context.font='11px ui-monospace,monospace';context.textAlign='right';context.fillText(max.toPrecision(3),x-8,y+4);context.fillText(min.toPrecision(3),x-8,y+height+4);context.restore()}
function bitmapFor(slice,min,max,log,scope){
  const key=`${state.colorMap}:${scope}:${slice.product}:${slice.permutation.join(',')}:${slice.layer}:${slice.rows}x${slice.columns}:${min}:${max}:${log}`,cached=state.bitmaps.get(key);if(cached){state.bitmaps.delete(key);state.bitmaps.set(key,cached);return cached}
  const canvas=document.createElement('canvas');canvas.width=slice.columns;canvas.height=slice.rows;const context=canvas.getContext('2d'),image=context.createImageData(slice.columns,slice.rows),pixels=image.data;
  const logMin=Math.log(Math.max(1e-12,min)),logSpan=Math.max(1e-12,Math.log(Math.max(min*1.0001,max))-logMin),linearSpan=Math.max(1e-12,max-min);
  for(let i=0;i<slice.values.length;i++){const value=slice.values[i],offset=i*4;if(!Number.isFinite(value)||value<=min){pixels[offset+3]=0;continue}let t=log?(Math.log(Math.max(1e-12,value))-logMin)/logSpan:(value-min)/linearSpan;t=Math.max(0,Math.min(1,t));const colors=palette(),scaled=Math.pow(t,.72)*(colors.length-1),low=Math.floor(scaled),high=Math.min(colors.length-1,low+1),mix=scaled-low,color=colors[low].map((channel,index)=>Math.round(channel+(colors[high][index]-channel)*mix)),fade=Math.min(1,t/.12),alpha=fade*fade*(3-2*fade);pixels[offset]=color[0];pixels[offset+1]=color[1];pixels[offset+2]=color[2];pixels[offset+3]=Math.round(255*alpha)}
  context.putImageData(image,0,0);lruSet(state.bitmaps,key,canvas,192);return canvas
}
async function drawOverview(product,canvas){
  const status=canvas.parentElement.querySelector('.product-status');status.hidden=false;status.textContent='Loading preview…';status.className='product-status';
  try{const axes=(product.view_axes||product.axes.slice(0,3)).map(name=>product.axes.indexOf(name)),depth=axes.length===3?product.shape[axes[0]]:1,count=Math.min(6,depth),layers=Array.from({length:count},(_,i)=>Math.round(i*(depth-1)/Math.max(1,count-1))),volume=await getVolume(product,axes,64),planeSize=volume.rows*volume.columns,slices=layers.map(layer=>({...volume,layer,values:volume.values.subarray(layer*planeSize,(layer+1)*planeSize)})),{context,width,height}=canvasSize(canvas),log=product.scale==='log',[min,max]=scaleBounds(product,log);if(axes.length===1){drawTrace(context,slices[0],30,28,width-48,height-62,min,max,log,state.theme==='light')}else{const boxWidth=width-52,boxHeight=height-75,dataAspect=volume.source_plane_shape[1]/Math.max(1,volume.source_plane_shape[0]),aspect=state.overviewAspect==='equal'?1:dataAspect,planeWidth=state.overviewAspect==='fit'?boxWidth:Math.min(boxWidth,boxHeight*aspect),planeHeight=state.overviewAspect==='fit'?boxHeight:Math.min(boxHeight,boxWidth/aspect),baseX=18+(boxWidth-planeWidth)/2,baseY=32+(boxHeight-planeHeight)/2;for(let i=count-1;i>=0;i--){const dx=i*6,dy=-i*6,image=bitmapFor(slices[i],min,max,log,'overview');context.save();context.globalAlpha=.22;context.drawImage(image,baseX+dx,baseY+dy,planeWidth,planeHeight);context.globalAlpha=.32;context.strokeStyle='#6177ff';context.lineWidth=1;context.strokeRect(baseX+dx,baseY+dy,planeWidth,planeHeight);context.restore()}}status.hidden=true}catch(error){status.hidden=false;status.textContent=`Preview failed · ${error.message} · click to retry`;status.className='product-status error';throw error}
}
async function build(){state.run=await fetch(staticBase?`${staticBase}/run.json`:'/api/run').then(response=>response.json());$('run-name').textContent=state.run.name;$('run-meta').textContent=`${state.run.products.length} captured products · ${state.run.created_at}`;const pipeline=$('pipeline');for(let i=0;i<state.run.products.length;i++){const product=state.run.products[i];if(i){const edge=document.createElement('div');edge.className='edge';edge.innerHTML=`<span>${product.operation||'transform'}</span>`;pipeline.append(edge)}const button=document.createElement('button');button.className='product';button.innerHTML=`<canvas aria-hidden="true"></canvas><span class="product-status">Loading preview…</span><strong>${product.name}</strong><span>${product.shape.join(' × ')} · ${product.dtype}</span>`;button.onclick=()=>{if(button.querySelector('.product-status').classList.contains('error'))drawOverview(product,button.querySelector('canvas')).catch(()=>{});selectProduct(product)};pipeline.append(button);drawOverview(product,button.querySelector('canvas')).catch(()=>{})}selectProduct(state.run.products[Math.min(2,state.run.products.length-1)])}
async function selectProduct(product){
  state.product=product;state.viewAxes=(product.view_axes||product.axes.slice(0,3)).map(name=>product.axes.indexOf(name));state.perm=[...state.viewAxes];state.layer=0;state.pixelDensity=96;state.scaleMin=0;state.scaleMax=1;state.logScale=product.scale==='log';state.viewMode='surface';
  const binary=product.units==='binary'||product.dtype==='bool';if(binary)state.logScale=false;$('minimum').value=0;$('maximum').value=100;$('minimum').disabled=binary;$('maximum').disabled=binary;$('log-scale').disabled=binary;$('log-scale').checked=state.logScale;syncScaleLabels();
  const viewSelect=$('view-mode');viewSelect.value='surface';viewSelect.querySelector('option[value="slices"]').disabled=state.viewAxes.length!==2;
  document.querySelectorAll('.product').forEach((element,index)=>element.classList.toggle('selected',state.run.products[index].id===product.id));$('inspect-title').textContent=product.name;$('inspect-description').textContent=product.metadata.description||`${product.axes.join(' × ')} data product`;$('shape').textContent=`${product.shape.join(' × ')} · ${product.axes.join(' × ')}`;$('payload').textContent=bytes(product.bytes);
  const select=$('permutation');select.innerHTML='';for(const order of permutations(state.viewAxes.length)){const axes=order.map(index=>state.viewAxes[index]),option=document.createElement('option');option.value=axes.join(',');option.textContent=axes.map(index=>product.axes[index]).join(' × ');select.append(option)}await Promise.all(state.viewAxes.map(axis=>getCoordinates(product,axis)));if(product!==state.product)return;syncLayer();scheduleDraw()
}
function syncLayer(){const sliced2D=state.perm.length===2&&state.viewMode==='slices',depth=state.perm.length===3||sliced2D?state.product.shape[state.perm[0]]:1,planeAxes=state.perm.slice(state.perm.length===3||sliced2D?1:0),nativeMaximum=Math.max(...planeAxes.map(axis=>state.product.shape[axis]),1),isSingleTrace=state.perm.length===1;$('layer').max=depth-1;state.layer=Math.min(state.layer,depth-1);$('layer').value=state.layer;$('layer-output').textContent=state.perm.length===3||sliced2D?`${state.product.axes[state.perm[0]]} ${coordinateLabel(state.perm[0],state.layer)} · ${state.layer+1}/${depth}`:'single plane';$('quality').max=nativeMaximum;state.pixelDensity=Math.min(state.pixelDensity,nativeMaximum);$('quality').value=state.pixelDensity;$('quality-output').textContent=`${state.pixelDensity} / ${nativeMaximum} px`;$('play').disabled=isSingleTrace||depth===1;$('save-animation').disabled=isSingleTrace||depth===1;$('save-layer').textContent=isSingleTrace||sliced2D?'Save plot PNG':'Save layer PNG'}
function syncScaleLabels(){if(!state.product)return;const[min,max]=displayBounds(),units=state.product.units?` ${state.product.units}`:'';if(state.logScale){const factor=(state.product.units||'').toLowerCase().includes('power')?10:20;$('minimum-output').textContent=`${(factor*Math.log10(min)).toFixed(1)} dB`;$('maximum-output').textContent=`${(factor*Math.log10(max)).toFixed(1)} dB`}else{$('minimum-output').textContent=`${min.toPrecision(3)}${units}`;$('maximum-output').textContent=`${max.toPrecision(3)}${units}`}}
function scheduleDraw(){state.renderVersion++;if(state.frame)return;state.frame=requestAnimationFrame(()=>{state.frame=0;drawVolume(state.renderVersion)})}
async function drawVolume(version){
  const canvas=$('volume'),product=state.product,perm=[...state.perm],selectedLayer=state.layer,depth=perm.length===3?product.shape[perm[0]]:1,count=Math.min(12,depth),contextLayers=Array.from({length:count},(_,i)=>Math.round(i*(depth-1)/Math.max(1,count-1)));
  setVolumeStatus('Loading data…');let contextSlices,selectedSlice;try{const sliced2D=perm.length===2&&state.viewMode==='slices',volumeLimit=sliced2D?Math.max(qualityLimit(),product.shape[perm[0]]):qualityLimit(),volume=await getVolume(product,perm,volumeLimit),planeSize=volume.rows*volume.columns,toSlice=layer=>({...volume,layer,values:volume.values.subarray(layer*planeSize,(layer+1)*planeSize)});contextSlices=state.isolate?[]:contextLayers.map(toSlice);selectedSlice=toSlice(sliced2D?0:selectedLayer)}catch(error){if(version===state.renderVersion)setVolumeStatus(`Unable to load: ${error.message}`,true);return}if(version!==state.renderVersion||product!==state.product)return;setVolumeStatus('');
  if(perm.length===1){const{context,width,height}=canvasSize(canvas),[displayMin,displayMax]=displayBounds(product),x=92,y=42,planeWidth=Math.max(100,width-135),planeHeight=Math.max(120,height-125),light=state.theme==='light';drawTrace(context,selectedSlice,x,y,planeWidth,planeHeight,displayMin,displayMax,state.logScale,light);drawSheetAxes(context,{x,y,width:planeWidth,height:planeHeight,xAxis:perm[0],yAxis:null,light});$('peak').textContent=(product.stats.max||selectedSlice.peak).toFixed(4);canvas._geometry={originX:x,originY:y,planeWidth,planeHeight,rows:1,columns:selectedSlice.columns,cellWidth:planeWidth/selectedSlice.columns,cellHeight:planeHeight,sourceRows:1,sourceColumns:selectedSlice.source_plane_shape[1],xAxis:perm[0],yAxis:null,layerAxis:null};return}
  if(perm.length===2&&state.viewMode==='slices'){
    const{context,width,height}=canvasSize(canvas),[displayMin,displayMax]=displayBounds(product),rowCount=selectedSlice.rows,shown=Math.min(12,rowCount),indices=Array.from({length:shown},(_,i)=>Math.round(i*(rowCount-1)/Math.max(1,shown-1))),traceWidth=Math.max(120,width-210),traceHeight=Math.max(100,height-190),offsetX=10*Math.cos(state.yaw),offsetY=-8+14*Math.sin(state.pitch),stackDx=offsetX*(shown-1),stackDy=offsetY*(shown-1),originX=(width-traceWidth-Math.abs(stackDx))/2-Math.min(0,stackDx),originY=(height-traceHeight-Math.abs(stackDy)-50)/2-Math.min(0,stackDy),makeRow=row=>({...selectedSlice,rows:1,depth:1,layer:row,values:selectedSlice.values.subarray(row*selectedSlice.columns,(row+1)*selectedSlice.columns)}),light=state.theme==='light';
    for(let i=shown-1;i>=0;i--){const row=indices[i];if(row===state.layer)continue;drawTrace(context,makeRow(row),originX+offsetX*i,originY+offsetY*i,traceWidth,traceHeight,displayMin,displayMax,state.logScale,light,state.opacity)}
    const selectedPosition=rowCount<=1?0:state.layer/(rowCount-1)*(shown-1),selectedX=originX+offsetX*selectedPosition,selectedY=originY+offsetY*selectedPosition;drawTrace(context,makeRow(state.layer),selectedX,selectedY,traceWidth,traceHeight,displayMin,displayMax,state.logScale,light,state.currentOpacity);drawSheetAxes(context,{x:selectedX,y:selectedY,width:traceWidth,height:traceHeight,xAxis:perm[1],yAxis:null,light});drawDepthAxis(context,perm[0],originX,originY,offsetX,offsetY,shown,selectedPosition,state.layer,light);$('peak').textContent=(product.stats.max||selectedSlice.peak).toFixed(4);canvas._geometry={originX:selectedX,originY:selectedY,planeWidth:traceWidth,planeHeight:traceHeight,rows:1,columns:selectedSlice.columns,cellWidth:traceWidth/selectedSlice.columns,cellHeight:traceHeight,sourceRows:1,sourceColumns:selectedSlice.source_plane_shape[1],xAxis:perm[1],yAxis:null,layerAxis:perm[0],stackOriginX:originX,stackOriginY:originY,offsetX,offsetY,slots:shown,selectedPosition};return
  }
  const {context,width,height}=canvasSize(canvas),rows=selectedSlice.rows,columns=selectedSlice.columns,sourceRows=selectedSlice.source_plane_shape[0],sourceColumns=selectedSlice.source_plane_shape[1],slots=state.isolate?1:count,offsetX=17*Math.cos(state.yaw),offsetY=-11+18*Math.sin(state.pitch),availableWidth=Math.max(80,width-190-Math.abs(offsetX)*(slots-1)),availableHeight=Math.max(80,height-120-Math.abs(offsetY)*(slots-1)),sourceAspect=state.aspect==='equal'?1:sourceColumns/sourceRows,planeWidth=state.aspect==='fit'?availableWidth:(availableWidth/availableHeight>sourceAspect?availableHeight*sourceAspect:availableWidth),planeHeight=state.aspect==='fit'?availableHeight:planeWidth/sourceAspect,cellWidth=planeWidth/columns,cellHeight=planeHeight/rows,stackWidth=planeWidth+Math.abs(offsetX)*(slots-1),stackHeight=planeHeight+Math.abs(offsetY)*(slots-1),originX=(width-stackWidth)/2+35+(offsetX<0?Math.abs(offsetX)*(slots-1):0),originY=(height-stackHeight-50)/2+Math.abs(offsetY)*(slots-1),[displayMin,displayMax]=displayBounds(product),bitmapScope=`detail:${state.scaleMin}:${state.scaleMax}:${state.logScale}`;
  context.imageSmoothingEnabled=false;
  function drawContextLayer(i,inFront){const layer=contextLayers[i];if(layer===selectedLayer)return;const distance=Math.abs(layer-selectedLayer)/Math.max(1,depth-1),image=bitmapFor(contextSlices[i],displayMin,displayMax,state.logScale,bitmapScope);context.save();context.globalAlpha=state.opacity;context.filter=`blur(${(.55+distance*1.8+(inFront?.35:0)).toFixed(2)}px)`;context.drawImage(image,originX+offsetX*i,originY+offsetY*i,planeWidth,planeHeight);context.restore();context.save();context.globalAlpha=state.opacity;context.strokeStyle=themeInk().line;context.strokeRect(originX+offsetX*i,originY+offsetY*i,planeWidth,planeHeight);context.restore()}
  if(!state.isolate){for(let i=contextSlices.length-1;i>=0;i--)if(contextLayers[i]>selectedLayer)drawContextLayer(i,false)}
  const selectedPosition=state.isolate?0:(depth<=1?0:selectedLayer/(depth-1)*(count-1)),selectedX=originX+offsetX*selectedPosition,selectedY=originY+offsetY*selectedPosition,selectedBitmap=bitmapFor(selectedSlice,displayMin,displayMax,state.logScale,bitmapScope);context.save();context.globalAlpha=state.currentOpacity;context.drawImage(selectedBitmap,selectedX,selectedY,planeWidth,planeHeight);context.restore();if(!state.isolate){context.strokeStyle=themeInk().strong;context.lineWidth=2.5;context.strokeRect(selectedX,selectedY,planeWidth,planeHeight)}
  if(!state.isolate){for(let i=contextSlices.length-1;i>=0;i--)if(contextLayers[i]<selectedLayer)drawContextLayer(i,true)}
  const xAxis=perm[perm.length-1],yAxis=perm.length>1?perm[perm.length-2]:null,light=state.theme==='light';drawSheetAxes(context,{x:selectedX,y:selectedY,width:planeWidth,height:planeHeight,xAxis,yAxis,light});if(perm.length===3&&!state.isolate)drawDepthAxis(context,perm[0],originX,originY,offsetX,offsetY,slots,selectedPosition,selectedLayer,light);$('peak').textContent=(product.stats.max||selectedSlice.peak).toFixed(4);canvas._geometry={originX:selectedX,originY:selectedY,planeWidth,planeHeight,rows,columns,cellWidth,cellHeight,sourceRows:selectedSlice.source_plane_shape[0],sourceColumns:selectedSlice.source_plane_shape[1],xAxis,yAxis,layerAxis:perm.length===3?perm[0]:null,stackOriginX:originX,stackOriginY:originY,offsetX,offsetY,slots,selectedPosition}
}
$('permutation').onchange=event=>{state.perm=event.target.value.split(',').map(Number);state.layer=0;syncLayer();scheduleDraw()};$('layer').oninput=event=>{state.layer=+event.target.value;syncLayer();scheduleDraw()};$('isolate').onchange=event=>{state.isolate=event.target.checked;$('opacity').disabled=state.isolate;scheduleDraw()};$('opacity').oninput=event=>{state.opacity=+event.target.value/100;$('opacity-output').textContent=`${event.target.value}%`;if(state.opacityLinked){state.currentOpacity=state.opacity;$('current-opacity').value=event.target.value;$('current-opacity-output').textContent=`${event.target.value}%`}scheduleDraw()};$('minimum').oninput=event=>{let value=+event.target.value,maximum=+$('maximum').value;if(value>=maximum){value=maximum-1;event.target.value=value}state.scaleMin=value/100;syncScaleLabels();scheduleDraw()};$('maximum').oninput=event=>{let value=+event.target.value,minimum=+$('minimum').value;if(value<=minimum){value=minimum+1;event.target.value=value}state.scaleMax=value/100;syncScaleLabels();scheduleDraw()};$('log-scale').onchange=event=>{state.logScale=event.target.checked;syncScaleLabels();scheduleDraw()};$('play').onclick=event=>{state.playing=!state.playing;event.target.textContent=state.playing?'Pause layers':'Play layers';clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>{const depth=state.perm.length===3?state.product.shape[state.perm[0]]:1;state.layer=(state.layer+1)%depth;syncLayer();scheduleDraw()},450)};
$('current-opacity').oninput=event=>{state.currentOpacity=+event.target.value/100;$('current-opacity-output').textContent=`${event.target.value}%`;if(state.opacityLinked){state.opacity=state.currentOpacity;$('opacity').value=event.target.value;$('opacity-output').textContent=`${event.target.value}%`}scheduleDraw()};
$('link-opacity').onclick=event=>{state.opacityLinked=!state.opacityLinked;event.target.setAttribute('aria-pressed',String(state.opacityLinked));event.target.textContent=`Link transparency: ${state.opacityLinked?'on':'off'}`;if(state.opacityLinked){state.opacity=state.currentOpacity;$('opacity').value=Math.round(state.opacity*100);$('opacity-output').textContent=`${Math.round(state.opacity*100)}%`;scheduleDraw()}};
$('quality').oninput=event=>{state.pixelDensity=+event.target.value;$('quality-output').textContent=`${state.pixelDensity} / ${event.target.max} px`;scheduleDraw()};
$('aspect').onchange=event=>{state.aspect=event.target.value;scheduleDraw()};
$('view-mode').onchange=event=>{state.viewMode=event.target.value;state.layer=0;syncLayer();scheduleDraw()};
$('overview-aspect').onchange=event=>{state.overviewAspect=event.target.value;document.querySelectorAll('.product canvas').forEach((canvas,index)=>drawOverview(state.run.products[index],canvas).catch(()=>{}))};
$('play').onclick=event=>{state.playing=!state.playing;event.target.textContent=state.playing?'Pause layers':'Play layers';clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>{const sliced2D=state.perm.length===2&&state.viewMode==='slices',depth=state.perm.length===3||sliced2D?state.product.shape[state.perm[0]]:1;state.layer=(state.layer+1)%depth;syncLayer();scheduleDraw()},450)};
$('volume').onclick=async event=>{const geometry=event.currentTarget._geometry;if(!geometry)return;const rect=event.currentTarget.getBoundingClientRect(),dx=event.clientX-rect.left-geometry.originX,dy=event.clientY-rect.top-geometry.originY;let column,row;if(geometry.u){const determinant=geometry.u.x*geometry.v.y-geometry.u.y*geometry.v.x;if(Math.abs(determinant)<1e-6)return;const across=(dx*geometry.v.y-dy*geometry.v.x)/determinant,down=(geometry.u.x*dy-geometry.u.y*dx)/determinant;column=Math.floor(across*geometry.columns);row=Math.floor(down*geometry.rows)}else{column=Math.floor(dx/geometry.cellWidth);row=Math.floor(dy/geometry.cellHeight)}if(column>=0&&column<geometry.columns&&row>=0&&row<geometry.rows){const slice=await getSlice(state.product,state.perm,state.layer),sourceX=geometry.columns<=1?0:Math.round(column*(geometry.sourceColumns-1)/(geometry.columns-1)),sourceY=geometry.rows<=1?0:Math.round(row*(geometry.sourceRows-1)/(geometry.rows-1)),parts=[`${state.product.axes[geometry.xAxis]} ${coordinateLabel(geometry.xAxis,sourceX)}`];if(geometry.yAxis!==null)parts.push(`${state.product.axes[geometry.yAxis]} ${coordinateLabel(geometry.yAxis,sourceY)}`);if(geometry.layerAxis!==null)parts.push(`${state.product.axes[geometry.layerAxis]} ${coordinateLabel(geometry.layerAxis,state.layer)}`);$('cell').textContent=`${parts.join(' · ')} = ${Number(slice.values[row*slice.columns+column]).toFixed(5)}`}};
function redrawAppearance(){document.documentElement.dataset.theme=state.theme;updateScale();document.querySelectorAll('.product canvas').forEach((canvas,index)=>drawOverview(state.run.products[index],canvas).catch(()=>{}));scheduleDraw()}
$('theme').onchange=event=>{state.theme=event.target.value;redrawAppearance()};
$('colormap').onchange=event=>{state.colorMap=event.target.value;redrawAppearance()};
let dragging=false,lastX=0,lastY=0;$('volume').onpointerdown=event=>{dragging=true;lastX=event.clientX;lastY=event.clientY;$('volume').setPointerCapture(event.pointerId)};$('volume').onpointermove=event=>{if(dragging){state.yaw=Math.max(-1.05,Math.min(1.05,state.yaw+(event.clientX-lastX)*.005));state.pitch=Math.max(-.65,Math.min(.65,state.pitch+(event.clientY-lastY)*.005));lastX=event.clientX;lastY=event.clientY;scheduleDraw()}};$('volume').onpointerup=()=>dragging=false;$('volume').onpointercancel=()=>dragging=false;$('volume').ondblclick=event=>{event.preventDefault();state.yaw=.3;state.pitch=0;scheduleDraw()};$('volume').onclick=async event=>{const geometry=event.currentTarget._geometry;if(!geometry)return;const rect=event.currentTarget.getBoundingClientRect(),x=Math.floor((event.clientX-rect.left-geometry.originX)/geometry.cellWidth),y=Math.floor((event.clientY-rect.top-geometry.originY)/geometry.cellHeight);if(x>=0&&x<geometry.columns&&y>=0&&y<geometry.rows){const slice=await getSlice(state.product,state.perm,state.layer),sourceX=geometry.columns<=1?0:Math.round(x*(geometry.sourceColumns-1)/(geometry.columns-1)),sourceY=geometry.rows<=1?0:Math.round(y*(geometry.sourceRows-1)/(geometry.rows-1)),parts=[`${state.product.axes[geometry.xAxis]} ${coordinateLabel(geometry.xAxis,sourceX)}`];if(geometry.yAxis!==null)parts.push(`${state.product.axes[geometry.yAxis]} ${coordinateLabel(geometry.yAxis,sourceY)}`);if(geometry.layerAxis!==null)parts.push(`${state.product.axes[geometry.layerAxis]} ${coordinateLabel(geometry.layerAxis,state.layer)}`);$('cell').textContent=`${parts.join(' · ')} = ${Number(slice.values[y*slice.columns+x]).toFixed(5)}`}};
function exportName(suffix,extension){const base=(state.product?.file?.split('/').pop().replace(/\.npy$/,'')||state.run.name).replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();return `${base}-${suffix}.${extension}`}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function saveCanvas(canvas,filename){canvas.toBlob(blob=>{if(blob)downloadBlob(blob,filename)},'image/png')}
async function saveSelectedLayer(){const product=state.product,sliced2D=state.perm.length===2&&state.viewMode==='slices',slice=await getDisplayedSlice(product,state.perm,state.layer),[min,max]=displayBounds(product),canvas=document.createElement('canvas');canvas.width=1200;canvas.height=820;const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#111827';context.font='600 24px system-ui';context.fillText(`${product.name} · ${state.perm.length===3||sliced2D?coordinateLabel(state.perm[0],state.layer):'selected view'}`,110,52);const width=850,height=600,x=190,y=90;context.imageSmoothingEnabled=false;if(state.perm.length===1||sliced2D){drawTrace(context,slice,x,y,width,height,min,max,state.logScale,true)}else{const image=bitmapFor(slice,min,max,state.logScale,`export:${state.scaleMin}:${state.scaleMax}:${state.logScale}`);context.save();context.globalAlpha=state.currentOpacity;context.drawImage(image,x,y,width,height);context.restore();context.strokeStyle='#111827';context.lineWidth=2;context.strokeRect(x,y,width,height)}drawSheetAxes(context,{x,y,width,height,xAxis:state.perm[state.perm.length-1],yAxis:state.perm.length>1&&!sliced2D?state.perm[state.perm.length-2]:null,light:true});saveCanvas(canvas,exportName(`layer-${state.layer}`,'png'))}
function saveStack(){const source=$('volume'),rect=source.getBoundingClientRect(),canvas=document.createElement('canvas');canvas.width=Math.round(rect.width);canvas.height=Math.round(rect.height);const context=canvas.getContext('2d'),geometry=source._geometry;context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(source,0,0,canvas.width,canvas.height);if(geometry){if(geometry.u)drawProjectedAxes(context,{x:geometry.originX,y:geometry.originY,u:geometry.u,v:geometry.v,xAxis:geometry.xAxis,yAxis:geometry.yAxis},true);else drawSheetAxes(context,{x:geometry.originX,y:geometry.originY,width:geometry.planeWidth,height:geometry.planeHeight,xAxis:geometry.xAxis,yAxis:geometry.yAxis,light:true});if(geometry.layerAxis!==null&&!state.isolate)drawDepthAxis(context,geometry.layerAxis,geometry.stackOriginX,geometry.stackOriginY,geometry.offsetX,geometry.offsetY,geometry.slots,geometry.selectedPosition,state.layer,true)}saveCanvas(canvas,exportName('stack','png'))}
function saveFullChain(){const canvases=[...document.querySelectorAll('.product canvas')],width=canvases.length*260+Math.max(0,canvases.length-1)*70,canvas=document.createElement('canvas');canvas.width=width;canvas.height=340;const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,width,340);context.fillStyle='#111827';context.font='600 22px system-ui';context.fillText(state.run.name,24,34);canvases.forEach((source,index)=>{const x=20+index*330;context.drawImage(source,x,55,220,200);const product=state.run.products[index];context.fillStyle='#111827';context.font='600 14px system-ui';context.textAlign='center';context.fillText(product.name,x+110,280);context.fillStyle='#4b5568';context.font='12px ui-monospace,monospace';context.fillText(product.shape.join(' × '),x+110,301);if(index<canvases.length-1){context.strokeStyle='#4b5568';context.beginPath();context.moveTo(x+230,155);context.lineTo(x+315,155);context.stroke();context.fillStyle='#4b5568';context.beginPath();context.moveTo(x+315,155);context.lineTo(x+305,149);context.lineTo(x+305,161);context.fill()}});context.textAlign='left';saveCanvas(canvas,`${state.run.name.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}-chain.png`)}
async function saveAnimation(){const button=$('save-animation'),product=state.product,perm=[...state.perm],depth=perm.length===3?product.shape[perm[0]]:1,frameCount=Math.min(depth,80),frameLayers=Array.from({length:frameCount},(_,i)=>Math.round(i*(depth-1)/Math.max(1,frameCount-1))),width=800,height=620,frameCanvas=document.createElement('canvas');frameCanvas.width=width;frameCanvas.height=height;const context=frameCanvas.getContext('2d'),encoder=new SpvizGifEncoder(width,height,10),[min,max]=displayBounds(product),x=130,y=80,planeWidth=610,planeHeight=440,xAxis=perm[perm.length-1],yAxis=perm.length>1?perm[perm.length-2]:null;button.disabled=true;try{for(let frame=0;frame<frameLayers.length;frame++){const layer=frameLayers[frame],slice=await getSlice(product,perm,layer),image=bitmapFor(slice,min,max,state.logScale,`gif:${state.scaleMin}:${state.scaleMax}:${state.logScale}`);context.fillStyle='#ffffff';context.fillRect(0,0,width,height);context.fillStyle='#111827';context.font='600 20px system-ui';context.textAlign='left';context.fillText(product.name,40,35);context.fillStyle='#4b5568';context.font='13px system-ui';context.fillText(perm.length===3?`${axisTitle(perm[0])}: ${coordinateLabel(perm[0],layer)} · frame ${frame+1}/${frameLayers.length}`:'single plane',40,57);context.imageSmoothingEnabled=false;context.save();context.globalAlpha=state.currentOpacity;context.drawImage(image,x,y,planeWidth,planeHeight);context.restore();context.strokeStyle='#111827';context.lineWidth=2;context.strokeRect(x,y,planeWidth,planeHeight);drawSheetAxes(context,{x,y,width:planeWidth,height:planeHeight,xAxis,yAxis,light:true});encoder.addFrame(context.getImageData(0,0,width,height).data);button.textContent=`Encoding GIF… ${frame+1}/${frameLayers.length}`;await new Promise(resolve=>setTimeout(resolve,0))}downloadBlob(encoder.finish(),exportName('layer-sweep','gif'))}finally{button.disabled=false;button.textContent='Save animation GIF'}}
async function saveSliceAnimation(){const button=$('save-animation'),product=state.product,depth=product.shape[state.perm[0]],frameCount=Math.min(depth,80),layers=Array.from({length:frameCount},(_,i)=>Math.round(i*(depth-1)/Math.max(1,frameCount-1))),width=800,height=620,frameCanvas=document.createElement('canvas');frameCanvas.width=width;frameCanvas.height=height;const context=frameCanvas.getContext('2d'),encoder=new SpvizGifEncoder(width,height,10),[min,max]=displayBounds(product),x=130,y=80,traceWidth=610,traceHeight=440;button.disabled=true;try{for(let frame=0;frame<layers.length;frame++){const layer=layers[frame],slice=await getDisplayedSlice(product,state.perm,layer);context.fillStyle='#ffffff';context.fillRect(0,0,width,height);context.fillStyle='#111827';context.font='600 20px system-ui';context.fillText(product.name,40,35);context.fillStyle='#4b5568';context.font='13px system-ui';context.fillText(`${axisTitle(state.perm[0])}: ${coordinateLabel(state.perm[0],layer)} · frame ${frame+1}/${layers.length}`,40,57);drawTrace(context,slice,x,y,traceWidth,traceHeight,min,max,state.logScale,true);drawSheetAxes(context,{x,y,width:traceWidth,height:traceHeight,xAxis:state.perm[1],yAxis:null,light:true});encoder.addFrame(context.getImageData(0,0,width,height).data);button.textContent=`Encoding GIF… ${frame+1}/${layers.length}`;await new Promise(resolve=>setTimeout(resolve,0))}downloadBlob(encoder.finish(),exportName('slice-sweep','gif'))}finally{button.disabled=false;button.textContent='Save animation GIF'}}
$('save-layer').onclick=saveSelectedLayer;$('save-stack').onclick=saveStack;$('save-chain').onclick=saveFullChain;$('save-animation').onclick=()=>state.perm.length===2&&state.viewMode==='slices'?saveSliceAnimation():saveAnimation();
const resizeObserver=new ResizeObserver(scheduleDraw);resizeObserver.observe($('volume').parentElement);let resizeTimer=0;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{document.querySelectorAll('.product canvas').forEach((canvas,index)=>drawOverview(state.run.products[index],canvas).catch(()=>{}));scheduleDraw()},100)});updateScale();build().catch(error=>{$('run-meta').textContent=`Unable to load run: ${error.message}`;setVolumeStatus('Unable to load run',true)});
